# Configuration for Rasa NLU.

language: en
pipeline: supervised_embeddings
# Configuration for Rasa Core.

policies:
  - name: KerasPolicy
    epochs: 200
    max_history: 6
  - name: MemoizationPolicy
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.3
    core_threshold: 0.3
    fallback_core_action_name: action_default_fallback
    fallback_nlu_action_name: action_default_fallback
    deny_suggestion_intent_name: negative
  - name: MappingPolicy
