## Sample File showing ngrok configuration. Do not use this as is for Production. This is for Testing only

version: "3.7"
services:

  va_api_gateway:
    init: true
    build: './va_api_gateway'
    environment:
      - PORT_APP=3000
      - WORKERS=1
      - THREADS=50
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - REDIS_PASS=Y7T6r5re3t8j9yr
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=eva
      - MONGODB_PASS=evapass
      - RASA_SERVER=http://va_custom_rasa:5005/model
    ports:
      - "3000:3000"
    volumes:
      - rasa_projects:/rasa_projects
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: redis-server --requirepass Y7T6r5re3t8j9yr
    ports:
      - '6379:6379'

  va_trainer_worker:
    build: './trainer_worker'
    volumes:
      - rasa_projects:/rasa_projects
    environment:
      - REDIS_PASS=Y7T6r5re3t8j9yr
    depends_on:
      - redis
      - va_api_gateway

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=eva
      - MONGO_INITDB_ROOT_PASSWORD=evapass
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    command: mongod  --logpath=/dev/null # --quiet

  va_ui_trainer:
    build: './ui-trainer'
    ports:
      - "8080:80"
    depends_on:
      - va_api_gateway


  va_action_server:
    build: './action_server'
    ports:
      - 5055:5055

  va_custom_rasa:
    build: './rasa_custom'
    ports:
      - 5005:5005
    volumes:
      - rasa_projects:/rasa_projects
    command:
      - run
      - --endpoints
      - config/endpoints.yml
      - --debug
      - --enable-api
      - --cors
      - "*"
    depends_on:
      - va_action_server

# Use only for testing not for Production.
# use url /inspect/http to get the ngrok url

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    command:
      - /bin/sh
      - -c
      - |
        ngrok http va_custom_rasa:5005
    depends_on:
      - va_custom_rasa

volumes:
  mongodb:
  rasa_projects: