version: '3.0'

## Docker compose main file

services:

  ##  Rasa Core main Container for PROD , This is an image downloaded from dockerhub , local files are mapped.

  rasa_core:
    image: rasa/rasa_core:latest
    ports:
      - 5005:5005
    volumes:
      - ./vol_chatbot_data/rasa/100/models/core:/app/models
      - ./vol_chatbot_data/rasa/100/config:/app/config
    command:
      - start
      - --core
      - models
      - -c
      - rest
      - --endpoints
      - config/endpoints.yml
      - -u
      - current/

  ## Rasa NLU image from Dockerhub , linked with the volume via bind mount

  rasa_nlu:
    image: rasa/rasa_nlu:latest-tensorflow
    ports:
      - "5000:5000"
    volumes:
      - ./vol_chatbot_data/rasa/100/models/nlu:/app/models
      - ./vol_chatbot_data/rasa/100/config:/app/config
    command:
      - start
      - --path
      - models
      - -c
      - config/nlu_config.yml


  ##  Rasa core actions server from dockerhub linked to local bind mount

  action_server:
    image: rasa/rasa_core_sdk:latest
    ports:
      - "5055:5055"
    volumes:
      - ./vol_chatbot_data/rasa/100/actions:/app/actions

  ## Redis conatiner for session manaegement for chatbot

  redis:
    image: redis:latest

  ## starting container for Angular Rasa Trainer

## Issue with launching this container hence committed
#  ui_trainer:
#    build: ./ui-trainer/.
#    ports:
#      - "5056:80"
##
