version: '3.0'

services:

  # Server Stack

  action_server:
    build: './action_server'
    ports:
      - 5055:5055
    container_name: action_server

  rasa:
    build: './rasa_custom'
    ports:
      - 5005:5005
#    volumes:
#    - "./vol_chatbot_data/rasa/server/models:/app/models"
#    - "./vol_chatbot_data/rasa/server/config:/app/config"
#    - "./vol_chatbot_data/rasa/server/logs:/app/logs"
#    - "./vol_chatbot_data/rasa/server/data:/app/data"
    command:
    - run
#    - --endpoints
#    - config/endpoints.yml
    - --debug
    - --enable-api
    - --cors
    - "*"
    depends_on:
      - action_server

  ## Trainer stack

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="eva"
      - MONGODB_PASS="evapass"
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    command: mongod  --logpath=/dev/null # --quiet

  api_gateway:
    container_name: api_gateway
    build: './api_gateway'
    environment:
      MONGODB_URL: mongodb://mongodb:27017
      MONGODB_NAME: eva_platform
      LOGGING: 'Yes'
      ACTION_SERVER_URL: http://action_server:5055/webhook
      RASA_SERVER_URL: http://rasa:5005/model
    ports:
      - "8089:8089"
    depends_on:
      - mongodb

  ui_trainer:
    container_name: ui_trainer
    build: './ui-trainer'
    ports:
      - "8080:80"
    depends_on:
      - api_gateway

volumes:
  mongodb: