version: "3.7"
services:

  sut:
    build: './tests'
    depends_on:
      - va_api_gateway
      - redis
      - mongodb
      - custom_rasa
      - trainer_worker
      - ui_trainer

  va_api_gateway:
    init: true
    build: './va_api_gateway'
    environment:
      - PORT_APP=3000
      - WORKERS=1
      - THREADS=50
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - RASA_SERVER=http://custom_rasa:5005/model
    ports:
      - "3000:3000"
    volumes:
      - rasa_projects:/rasa_projects
    depends_on:
      - redis

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'

  trainer_worker:
    build: './trainer_worker'
    volumes:
      - rasa_projects:/rasa_projects
    depends_on:
      - redis
      - va_api_gateway

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="eva"
      - MONGODB_PASS="evapass"
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    command: mongod  --logpath=/dev/null # --quiet

  ui_trainer:
    container_name: ui_trainer
    build: './ui-trainer'
    ports:
      - "8080:80"
    depends_on:
      - va_api_gateway


  action_server:
    build: './action_server'
    container_name: action_server
    ports:
      - 5055:5055

  custom_rasa:
    build: './rasa_custom'
    ports:
      - 5005:5005
    volumes:
      - rasa_projects:/rasa_projects
    command:
      - run
      - --endpoints
      - config/endpoints.yml
      - --credentials
      - config/credentials.yml
      - --debug
      - --enable-api
      - --cors
      - "*"
    depends_on:
      - action_server

volumes:
  mongodb:
  rasa_projects: