version: '3.0'

services:

  # Server Stack

#  action_server_old:
#    image: rasa/rasa-sdk:latest
#    ports:
#      - 5055:5055
#    container_name: "action_server"
#    volumes:
#    - "./vol_chatbot_data/rasa/server/actions:/app/actions"

  action_server:
    container_name: action_server
    build: './actions-endpoint'
    ports:
      - "5055:5055"
    volumes:
      - "./actions-endpoint/actions:/app/actions"
    depends_on:
      - api_gateway

  rasa:
    image: rasa/rasa:latest-full
    ports:
      - 5005:5005
    volumes:
    - "./vol_chatbot_data/rasa/server/models:/app/models"
    - "./vol_chatbot_data/rasa/server/config:/app/config"
    - "./vol_chatbot_data/rasa/server/logs:/app/logs"
    - "./vol_chatbot_data/rasa/server/data:/app/data"
    command:
    - run
    - --endpoints
    - config/endpoints.yml
    - --debug
    - --enable-api
    depends_on:
      - action_server

  skype_connector:
    container_name: skype_connector
    build: './conn-skype'
    depends_on:
      - rasa

  ## Trainer stack

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="eva"
      - MONGODB_PASS="evapass"
    volumes:
      - ./vol_chatbot_data/database/db:/data/db
    ports:
      - 27017:27017
    command: mongod  --logpath=/dev/null # --quiet

  api_gateway:
    container_name: api_gateway
    volumes:
      - ./vol_chatbot_data:/vol_chatbot_data
    build: './api_gateway'
    ports:
      - "8089:8089"
    depends_on:
      - mongodb

  ui_trainer:
    container_name: ui_trainer
    build: './ui-trainer'
    ports:
      - "8080:80"
    depends_on:
      - api_gateway
