version: "3.7"
services:

  va_api_gateway:
    init: true
    #image: docker.pkg.github.com/navigateconsulting/virtual-assistant/va_api_gateway:latest
    image: navigateconsulting/va_api_gateway
    environment:
      - PORT_APP=3000
      - WORKERS=1
      - THREADS=50
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - RASA_SERVER=http://va_custom_rasa:5005/model
    ports:
      - "3000:3000"
    volumes:
      - rasa_projects:/rasa_projects
    depends_on:
      - redis

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'

  va_trainer_worker:
    #image: docker.pkg.github.com/navigateconsulting/virtual-assistant/trainer_worker:latest
    image: navigateconsulting/va_trainer_worker
    volumes:
      - rasa_projects:/rasa_projects
    depends_on:
      - redis
      - va_api_gateway

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="eva"
      - MONGODB_PASS="evapass"
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    command: mongod  --logpath=/dev/null # --quiet

  va_ui_trainer:
    #image: docker.pkg.github.com/navigateconsulting/virtual-assistant/ui_trainer:latest
    image: navigateconsulting/va_ui_trainer
    ports:
      - "8080:80"
    depends_on:
      - va_api_gateway


  va_action_server:
    #image: docker.pkg.github.com/navigateconsulting/virtual-assistant/action_server:latest
    image: navigateconsulting/va_action_server
    ports:
      - 5055:5055

  va_custom_rasa:
    #image: docker.pkg.github.com/navigateconsulting/virtual-assistant/custom_rasa:latest
    image: navigateconsulting/va_custom_rasa
    ports:
      - 5005:5005
    volumes:
      - rasa_projects:/rasa_projects
    command:
      - run
      - --endpoints
      - config/endpoints.yml
      - --credentials
      - config/credentials.yml
      - --debug
      - --enable-api
      - --cors
      - "*"
    depends_on:
      - va_action_server

volumes:
  mongodb:
  rasa_projects: